### ISSUE TITLE
未知的报错

### ISSUE THREAD

**Issue by Sokwva** [orzogc/acfundanmu#1]
未知的item.SingalType： CommonStateSignalChatReady

`
2020/06/22 00:28:33 未知的item.SingalType： CommonStateSignalChatReady
♂5zQog3STYtk↕�ȭ6↕♀菊之先生→�☺
unknown↕Phttps://imgs.aixifan.com/style/image/201907/4RJ8wJePz9sL3jVGm4wecMmADdbLz8Yu.jpg→Phttps://imgs.aixifan.com/style/image/201907/4RJ8wJePz9sL3jVGm4wecMmADdbLz8Yu.jpg↑☻
`
`
2020/06/22 00:30:44 未知的item.SingalType： CommonStateSignalChatEnd
♂5zQog3STYtk►☻
`
`
2020/06/22 00:31:39 未知的item.SingalType： CommonStateSignalChatReady
♂3ZLeeRX-amQ↕���☼↕♀蒂德利特→�☺
unknown↕=https://imgs.aixifan.com/content/2020_03_29/1585420153037.JPG→=https://imgs.aixifan.com/content/2020_03_29/1585420153037.JPG↑☻
`

**Comment by orzogc** [comment]
应该是猴子更新了proto，暂时无法处理，得等大佬更新
能正常使用的话不用管

**Comment by Sokwva** [comment]
好

**Comment by wpscott** [comment]
未知的payload建议base64编码后输出，方便调试
