### ISSUE TITLE
请问如果ws发送的RegisterRequest如果有错会发生什么

### ISSUE THREAD

**Issue by kanoyami** [orzogc/acfundanmu#5]
我按照实现用Nodejs重写了一遍acfundanmu
但是在我发送RegisterRequest的时候，会直接断开ws的连接
偶尔有成功的时候会保持对话，但是绝大多数情况会断开连接，断开连接是代表着这个RegisterRequest是错误的吗

**Comment by orzogc** [comment]
加密错了吧，应该是aes-128-cbc

**Comment by kanoyami** [comment]
> 加密错了吧，应该是aes-128-cbc

谢谢，知道了，请问padding规则是什么呢

**Comment by orzogc** [comment]
aes-128-cbc要求加密文本的长度必须是blocksize（16字节）乘以正数，通常长度是不够的，需要padding（PKCS#7），就是最后一个block的长度不是16字节的话，重复填充未够的长度至16字节，比如最后一个block的长度是12字节，就需要填充 `0x04` 4次，解密时的unpadding是反过来的
nodejs一般会自动padding和unpadding：https://nodejs.org/api/crypto.html#crypto_cipher_setautopadding_autopadding

**Comment by kanoyami** [comment]
我知道这些，原数据长度为106，nodejs autopading之后得到加密数据长度是112，但是我解密正确的密文解析出来的长度是128，数据内容和原数据长度则完全一样

**Comment by orzogc** [comment]
> 我知道这些，原数据长度为106，nodejs autopading之后得到加密数据长度是112，但是我解密正确的密文解析出来的长度是128，数据内容和原数据长度则完全一样

不明白你的意思，能再说清楚一点吗？解密的密文哪里来的？

**Comment by orzogc** [comment]
忘了说，如果最后一个block刚好是16字节，会填充16个 `0x10`

**Comment by kanoyami** [comment]
> > 我知道这些，原数据长度为106，nodejs autopading之后得到加密数据长度是112，但是我解密正确的密文解析出来的长度是128，数据内容和原数据长度则完全一样
> 
> 不明白你的意思，能再说清楚一点吗？解密的密文哪里来的？

我在chrome的调试的xhr里找到浏览器发送login请求获得的AcSecurity,然后用这个反过来解密ws中抓到第一个上传包，也就是RegisterRequest，然后用根据规则解密出来，可以看到header里面decodedPayloadLen是106，然后以int32读取第8位的数据得到的长度是128。
我自己对长度为106的body进行加密，使用nodejs的autopadding进行填充，得到的密文长度是112。

**Comment by orzogc** [comment]
这个是看最后一个字节的数字来unpadding的，所以最后一个字节是多少？

**Comment by kanoyami** [comment]
> 这个是看最后一个字节的数字来unpadding的，所以最后一个字节是多少？

具体是指的哪个包的最后一个字节呢？
如果是抓来的ws包 最后一个字节是`0xC4`
如果是加密前的payload 最后一个字节是`0x70`

**Comment by kanoyami** [comment]
> 这个是看最后一个字节的数字来unpadding的，所以最后一个字节是多少？

我知道了，我重新读取了正确包的从iv开始到最后的长度，比以int32读取第8位的数据少16，我再基础上加了16，现在可以得到正确的服务器返回了，所以以int32读取第8位数据应当是包含iv和加密包的总长度

**Comment by orzogc** [comment]
本来就是包含的，具体看代码

**Comment by kanoyami** [comment]
谢谢啦，我看的danmuku的表格，所以理解上有点问题了
